### PR TITLE
Some improvements for tracking pixel

### LINKED ISSUE #3: Tracking Pixel Broken
The tracking pixel was appending /mtracking.gif after the urlencoded vars causing the tracking pixel not to work. The fix is below.

**/multitracker/view.php**

line: 4
`" />`

**/multitracker/controller.php**

line: 40
`$this->set('mautic_base_url', $this->mautic_base_url . '/mtracking.gif?d=' . $encodedAttrs);`

### PR DESCRIPTION
**Pull request by hissy**
Hi Mautic folks,

concrete5 is also a member of Symfony world.
Let's use Request component to get correct request information!

Plus, some fixes for tracking, caching, editing, language issues.
This PR should fixes #3 .

Thanks for the wonderful integration for c5!

### CODE REVIEW

**Comment by dbhurley** [comment]
+1 Thanks for the updates!

**Comment by escopecz** [comment]
I've tested this PR on a fresh C5 v5.7.5.2 and I got this error message when inserting a Mautic form:
c5-error

### Steps to reproduce
1. Add the Mautic - C5 addon to the `packages` folder.
2. Mautic addon will appear in the _Add functionality_ section.
3. Hit the _Install_ button.
4. Add a new block - Mautic Form.
5. Fill in the URL to a Mautic instance and a Form ID.
6. Save.

I get the error when I try to go to the edit mode.

**Comment by hissy** [comment]
This request is about Tracker block, and I didn't any modify to Form block.
But I can check this error.
Could you tell me the debug information about this?
1. Go to Dashboard > System & Settings > Environment > Debug Settings
2. Select "Output error information to site users" and "Show the debug error output" then hit the Save button

**Comment by hissy** [comment]
Oh, I'm sorry. I found a issue and pushed the fix.

**Comment by escopecz** [comment]
Works for me now :+1: 

I think we should release a new version.

**Comment by hissy** [comment]
Any updates on this?

**Comment by dbhurley** [comment]
Should have been merged! Thank you for bringing it up again.

**Comment by hissy** [comment]
Thanks!

**Comment by hissy** [comment]
Mautic on concrete5 marketplace is still 0.9.1. Are you have any problems on this?

http://www.concrete5.org/marketplace/addons/mautic

**Pull request merged**
